const USER_TYPES = {
    ADMIN: 'admin',
    CUSTOMER: 'customer'
}

const NOTIFICATION_STATUSES = {
    MAJOR: 'MAJOR',
    MEDIUM: 'MEDIUM',
    MINOR: 'MINOR' 
}

const COVID_SURVIVE_HOURS = 72

const MAX_DIST_PATHOGEN_BEARING_TRAVEL_DURING_SNEEZES_M = 8

module.exports = {
    USER_TYPES,
    NOTIFICATION_STATUSES,
    COVID_SURVIVE_HOURS,
    MAX_DIST_PATHOGEN_BEARING_TRAVEL_DURING_SNEEZES_M
}